### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by uuleaf** [gmftbyGMFTBY/GPT2Dialog#2]
老师好，
不知道老师能在 
https://github.com/Morizeyao/GPT2-Chinese/ 的基础上，加上 https://github.com/huggingface/transformers/tree/master/examples/pplm 可控文本生成的功能

我这边可以有偿 QQ2027725943

**Comment by gmftbyGMFTBY** [comment]
This code is not my repo. Maybe you can ask the author of the codes GPT2-chitchat (just search it).

**Comment by uuleaf** [comment]
谢谢老师
